export const SET_FILTER_BY_SEARCH = 'SET_FILTER_BY_SEARCH';
export const SET_FILTER_BY_SECTIONS = 'SET_FILTER_BY_SECTIONS';
export const SET_FILTER_BY_STYLES = 'SET_FILTER_BY_STYLES';
export const SET_PAGES = 'SET_PAGES';

export const RESET_FILTER = 'RESET_FILTER';
